# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\dynamic_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dynamic_Form(object):
    def setupUi(self, dynamic_Form):
        dynamic_Form.setObjectName("dynamic_Form")
        dynamic_Form.resize(977, 995)
        dynamic_Form.setStyleSheet("background-color: rgb(255, 234, 234);")
        self.gridLayout = QtWidgets.QGridLayout(dynamic_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.hint = QtWidgets.QLabel(dynamic_Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.hint.setFont(font)
        self.hint.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hint.setText("")
        self.hint.setAlignment(QtCore.Qt.AlignCenter)
        self.hint.setObjectName("hint")
        self.verticalLayout.addWidget(self.hint)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.img2 = QtWidgets.QLabel(dynamic_Form)
        self.img2.setAutoFillBackground(False)
        self.img2.setStyleSheet("background-color: rgba(255, 255, 255, 255\n"
");")
        self.img2.setText("")
        self.img2.setObjectName("img2")
        self.verticalLayout_2.addWidget(self.img2)
        self.img3 = QtWidgets.QLabel(dynamic_Form)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.img3.setFont(font)
        self.img3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.img3.setAutoFillBackground(False)
        self.img3.setStyleSheet("background-color: rgba(255, 0, 255, 50);")
        self.img3.setText("")
        self.img3.setObjectName("img3")
        self.verticalLayout_2.addWidget(self.img3)
        self.img4 = QtWidgets.QLabel(dynamic_Form)
        self.img4.setAutoFillBackground(False)
        self.img4.setStyleSheet("background-color: rgba(255, 0, 255, 50);")
        self.img4.setText("")
        self.img4.setObjectName("img4")
        self.verticalLayout_2.addWidget(self.img4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.img1 = QtWidgets.QLabel(dynamic_Form)
        self.img1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.img1.setAutoFillBackground(False)
        self.img1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.img1.setText("")
        self.img1.setObjectName("img1")
        self.horizontalLayout.addWidget(self.img1)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.hint_2 = QtWidgets.QLabel(dynamic_Form)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(22)
        self.hint_2.setFont(font)
        self.hint_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hint_2.setAlignment(QtCore.Qt.AlignCenter)
        self.hint_2.setObjectName("hint_2")
        self.verticalLayout.addWidget(self.hint_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(2, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 2)

        self.retranslateUi(dynamic_Form)
        QtCore.QMetaObject.connectSlotsByName(dynamic_Form)

    def retranslateUi(self, dynamic_Form):
        _translate = QtCore.QCoreApplication.translate
        dynamic_Form.setWindowTitle(_translate("dynamic_Form", "Form"))
        self.hint_2.setText(_translate("dynamic_Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ff0000;\">提醒事項</span></p><p align=\"center\">請正視鏡頭1~3秒鐘</p><p align=\"center\">請將口罩脫下露出下巴</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dynamic_Form = QtWidgets.QWidget()
    ui = Ui_dynamic_Form()
    ui.setupUi(dynamic_Form)
    dynamic_Form.show()
    sys.exit(app.exec_())
