# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\user_only.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(913, 770)
        self.img1 = QtWidgets.QLabel(Form)
        self.img1.setGeometry(QtCore.QRect(0, 0, 911, 661))
        self.img1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.img1.setAutoFillBackground(False)
        self.img1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.img1.setText("")
        self.img1.setObjectName("img1")
        self.img2 = QtWidgets.QLabel(Form)
        self.img2.setGeometry(QtCore.QRect(30, 90, 111, 151))
        self.img2.setAutoFillBackground(False)
        self.img2.setStyleSheet("background-color: rgba(180, 180, 180, 180);")
        self.img2.setText("")
        self.img2.setObjectName("img2")
        self.img3 = QtWidgets.QLabel(Form)
        self.img3.setGeometry(QtCore.QRect(30, 250, 111, 151))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.img3.setFont(font)
        self.img3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.img3.setAutoFillBackground(False)
        self.img3.setStyleSheet("background-color: rgba(255, 0, 255, 50);")
        self.img3.setText("")
        self.img3.setObjectName("img3")
        self.img4 = QtWidgets.QLabel(Form)
        self.img4.setGeometry(QtCore.QRect(30, 410, 111, 151))
        self.img4.setAutoFillBackground(False)
        self.img4.setStyleSheet("background-color: rgba(255, 0, 255, 50);")
        self.img4.setText("")
        self.img4.setObjectName("img4")
        self.hint = QtWidgets.QLabel(Form)
        self.hint.setGeometry(QtCore.QRect(0, 50, 171, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.hint.setFont(font)
        self.hint.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hint.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.hint.setAlignment(QtCore.Qt.AlignCenter)
        self.hint.setObjectName("hint")
        self.hint2 = QtWidgets.QLabel(Form)
        self.hint2.setGeometry(QtCore.QRect(0, 660, 911, 111))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(22)
        self.hint2.setFont(font)
        self.hint2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.hint2.setAlignment(QtCore.Qt.AlignCenter)
        self.hint2.setObjectName("hint2")
        self.hint2.raise_()
        self.img1.raise_()
        self.img2.raise_()
        self.img3.raise_()
        self.img4.raise_()
        self.hint.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hint.setText(_translate("Form", "Name"))
        self.hint2.setText(_translate("Form", "<html><head/><body><p align=\"center\">請靠近鏡頭<br/>請露出下巴與眉毛</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
