# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Show_from(object):
    def setupUi(self, Show_from):
        Show_from.setObjectName("Show_from")
        Show_from.resize(802, 990)
        Show_from.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.img1 = QtWidgets.QLabel(Show_from)
        self.img1.setGeometry(QtCore.QRect(0, 130, 800, 600))
        self.img1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.img1.setAutoFillBackground(False)
        self.img1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.img1.setText("")
        self.img1.setObjectName("img1")
        self.hint = QtWidgets.QLabel(Show_from)
        self.hint.setGeometry(QtCore.QRect(0, 70, 801, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.hint.setFont(font)
        self.hint.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hint.setText("")
        self.hint.setAlignment(QtCore.Qt.AlignCenter)
        self.hint.setObjectName("hint")
        self.hint_2 = QtWidgets.QLabel(Show_from)
        self.hint_2.setGeometry(QtCore.QRect(0, 750, 801, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hint_2.setFont(font)
        self.hint_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hint_2.setAlignment(QtCore.Qt.AlignCenter)
        self.hint_2.setObjectName("hint_2")
        self.img2 = QtWidgets.QLabel(Show_from)
        self.img2.setGeometry(QtCore.QRect(660, 140, 131, 171))
        self.img2.setAutoFillBackground(False)
        self.img2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.img2.setText("")
        self.img2.setObjectName("img2")
        self.img3 = QtWidgets.QLabel(Show_from)
        self.img3.setGeometry(QtCore.QRect(20, 300, 111, 101))
        self.img3.setAutoFillBackground(False)
        self.img3.setStyleSheet("background-color: rgba(255, 0, 255, 50);")
        self.img3.setText("")
        self.img3.setObjectName("img3")
        self.img4 = QtWidgets.QLabel(Show_from)
        self.img4.setGeometry(QtCore.QRect(20, 410, 111, 101))
        self.img4.setAutoFillBackground(False)
        self.img4.setStyleSheet("background-color: rgba(255, 0, 255, 50);")
        self.img4.setText("")
        self.img4.setObjectName("img4")

        self.retranslateUi(Show_from)
        QtCore.QMetaObject.connectSlotsByName(Show_from)

    def retranslateUi(self, Show_from):
        _translate = QtCore.QCoreApplication.translate
        Show_from.setWindowTitle(_translate("Show_from", "Form"))
        self.hint_2.setText(_translate("Show_from", "提醒事項"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Show_from = QtWidgets.QWidget()
    ui = Ui_Show_from()
    ui.setupUi(Show_from)
    Show_from.show()
    sys.exit(app.exec_())
